
services:

  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    networks:
      - retail-network

  productoservice:
    build:
      context: .
      dockerfile: ProductoService/Dockerfile
    container_name: productoservice
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductoDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    networks:
      - retail-network

  transaccionservice:
    build:
      context: .
      dockerfile: TransaccionService/Dockerfile
    container_name: transaccionservice
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TransaccionDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    networks:
      - retail-network

  inventarioservice:
    build:
      context: .
      dockerfile: InventarioService/Dockerfile
    container_name: inventarioservice
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InventarioDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    networks:
      - retail-network

  gateway:
    build:
      context: .
      dockerfile: Gateway.OcelotGateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - retail-network

networks:
  retail-network:
    driver: bridge